name: geodesy
description: A Dart library for implementing geodesic and trigonometric calculations based on a spherical Earth model for working with points and paths such as distances, bearings and destinations
version: 0.1.1
homepage: https://github.com/wingkwong/geodesy
author: WONG, Wing Kam <wingkwong.code@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'
