name: geodesy
description: A Dart library for geodesic and trigonometric calculations working with points and paths
version: 0.10.2
homepage: https://github.com/wingkwong/geodesy

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  latlong2: ^0.9.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.16.8
